<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sig</string>
		<string>mod</string>
		<string>thm</string>
	</array>
	<key>name</key>
	<string>Abella</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Empty Line</string>
			<key>match</key>
			<string>\s*</string>
			<key>name</key>
			<string>meta.emptyline</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.abella</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Sig/Module Header</string>
			<key>match</key>
			<string>(sig|module)\s+([a-zA-Z_]+)\s*.</string>
			<key>name</key>
			<string>meta.section</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(type|kind)\s+(([a-z][a-zA-Z_]*)\s*,\s*)*([a-z][a-zA-Z_]*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.abella</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Type/Kind Declaration</string>
			<key>end</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.function.abella</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rhs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.abella</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Specification/Import Commands</string>
			<key>match</key>
			<string>(Specification|Import)\s+("[a-zA-Z_]+")\s*.</string>
			<key>name</key>
			<string>meta.section</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(Theorem)\s+([a-z][a-zA-Z_]*)\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.abella</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Theorem Declaration</string>
			<key>end</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.function.abella</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rhs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(Define|CoDefine)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.abella</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Define/CoDefine</string>
			<key>end</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.function.abella</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rhs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(induction|coinduction|intros|case|search|apply|backchain|unfold|assert|exists|split|left|right|permute|inst|cut|monotone|undo|skip|abort|clear|abbrev|unabbrev)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.abella</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tactic</string>
			<key>end</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.tactic.abella</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^</string>
			<key>comment</key>
			<string>Rule Declaration</string>
			<key>end</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.rule.abella</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rhs</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\%</string>
					<key>comment</key>
					<string>Line Comment</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.abella</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\%\{</string>
					<key>comment</key>
					<string>Block Comment</string>
					<key>end</key>
					<string>\}\%</string>
					<key>name</key>
					<string>comment.block.abella</string>
				</dict>
			</array>
		</dict>
		<key>rhs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Just Keywords</string>
					<key>match</key>
					<string>\b(type|false|o|olist|nil|::|prop|pi|forall|exists|nabla)\b</string>
					<key>name</key>
					<string>constant.language.abella</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Built in Connectives</string>
					<key>match</key>
					<string>-&gt;|\\/|/\\|=&gt;|:=|=|\|-</string>
					<key>name</key>
					<string>keyword.operator.abella</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Top-Level Connectives</string>
					<key>match</key>
					<string>:-|,|;|by</string>
					<key>name</key>
					<string>keyword.other.abella</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Grouping Operators</string>
					<key>match</key>
					<string>\{|\}|\(|\)|\\</string>
					<key>name</key>
					<string>keyword.character.escape</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Meta Variables</string>
					<key>match</key>
					<string>[A-Z_][a-zA-Z_0-9]*</string>
					<key>name</key>
					<string>variable.language.abella</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Standard Variables</string>
					<key>match</key>
					<string>[a-z][a-zA-Z_0-9]*</string>
					<key>name</key>
					<string>variable.parameter.abella</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.abella</string>
	<key>uuid</key>
	<string>6b5536a4-8b6d-4f22-9470-66f5f4d8a052</string>
</dict>
</plist>
